### ISSUE TITLE
`--region` is broken

### ISSUE THREAD

**Issue by mzy2240** [sengaya/aws-micro-cli#14]

**Comment by sengaya** [comment]
Could you give an example and information about you environment (especially which OS)?

**Comment by mzy2240** [comment]
```shell
#11 [ 6/16] RUN aws-micro --region
#11 0.190 Missing value for the optional argument '--region'.
#11 ERROR: process "/bin/sh -c aws-micro --region" did not complete successfully: exit code: 1
------
 > [ 6/16] RUN aws-micro --region:
0.190 Missing value for the optional argument '--region'.
```
Its a debian docker image (latest debian:bullseye-slim)

**Comment by sengaya** [comment]
`--region` expects a value, such as `eu-central-1`

In case I misunderstood, please share the full command (you can obfuscate the URL of course). Please also compare what the `aws` cli would return and share the results as well. Thanks!

**Comment by mzy2240** [comment]
ic. I expected the usage of `--region` is the same as `--version`, but seems Im wrong (my actual full command is really just `aws-micro --region`). If that is the case, feel free to close the issue.

**Comment by sengaya** [comment]
ok, in this case I close the issue. For reference, this is the output of the `aws` cli:
```
$ aws --region

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --region: expected one argument
```
